# Generated by Django 6.1 on 2026-09-01 18:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        # makemigrations never generates this, and without it the geometry columns below cannot be created at all.
        # Needs a superuser, which our `airmax` role has on RDS through rds_superuser. The least-privilege role the
        # Lambda connects with does not.
        # See: https://docs.djangoproject.com/en/6.1/ref/contrib/gis/install/postgis/
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='City',
            fields=[
                ('refnis', models.IntegerField(primary_key=True, serialize=False)),
                ('name_nl', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('source_city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('is_mobile', models.BooleanField()),
                ('entity', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(choices=[('co', 'CO'), ('no2', 'NO₂'), ('o3', 'O₃'), ('pm10', 'PM10'), ('pm25', 'PM2.5'), ('so2', 'SO₂')], max_length=10)),
                ('event_time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('mg/m³', 'mg/m³'), ('µg/m³', 'µg/m³')], max_length=10)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('is_analysis', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='airmax.city')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='airmax.location')),
            ],
            options={
                'indexes': [models.Index(fields=['event_time'], name='measurement_event_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'parameter', 'event_time'), name='measurement_natural_key'), models.CheckConstraint(condition=models.Q(models.Q(('parameter', 'co'), ('unit', 'mg/m³')), models.Q(('parameter', 'no2'), ('unit', 'µg/m³')), models.Q(('parameter', 'o3'), ('unit', 'µg/m³')), models.Q(('parameter', 'pm10'), ('unit', 'µg/m³')), models.Q(('parameter', 'pm25'), ('unit', 'µg/m³')), models.Q(('parameter', 'so2'), ('unit', 'µg/m³')), _connector='OR'), name='measurement_unit_matches_parameter')],
            },
        ),
    ]
