# Generated by Django 6.1 on 2026-08-29 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airmax', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=2)),
                ('is_mobile', models.BooleanField()),
                ('entity', models.CharField(max_length=50)),
                ('sensor_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=10)),
                ('event_time', models.DateTimeField()),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_analysis', models.BooleanField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='airmax.location')),
            ],
            options={
                'indexes': [models.Index(fields=['event_time'], name='measurement_event_time_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'parameter', 'event_time'), name='measurement_natural_key'), models.CheckConstraint(condition=models.Q(models.Q(('parameter', 'co'), ('unit', 'mg/m³')), models.Q(('parameter', 'no2'), ('unit', 'µg/m³')), models.Q(('parameter', 'o3'), ('unit', 'µg/m³')), models.Q(('parameter', 'pm10'), ('unit', 'µg/m³')), models.Q(('parameter', 'pm25'), ('unit', 'µg/m³')), models.Q(('parameter', 'so2'), ('unit', 'µg/m³')), _connector='OR'), name='measurement_unit_matches_parameter')],
            },
        ),
    ]
