# Generated by Django 6.1 on 2026-08-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airmax", "0002_location_measurement"),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='entity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='sensor_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='parameter',
            field=models.CharField(choices=[('co', 'CO'), ('no2', 'NO₂'), ('o3', 'O₃'), ('pm10', 'PM10'), ('pm25', 'PM2.5'), ('so2', 'SO₂')], max_length=10),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.CharField(choices=[('mg/m³', 'mg/m³'), ('µg/m³', 'µg/m³')], max_length=10),
        ),
    ]
